// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20250304060511_WEB")]
    partial class WEB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccessLayer.Student", b =>
                {
                    b.Property<int>("rollno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rollno"), 1L, 1);

                    b.Property<string>("branch")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StudentBranch");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StudentName");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentYear");

                    b.HasKey("rollno");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
